### ISSUE TITLE
feat: Implement GC proposal

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#1122]
## Motivation

When trying to compile the application which are written in GC support languages into WASM. One of the biggest problems is that WASM has not support GC.

Some discussion about this in GraalVM issue: https://github.com/oracle/graal/issues/3391 

To make it getting much more feasible, we would like to implement WebAssembly GC proposal.

## Details

1. To implement GC proposal, we have to implement the following three proposals: 

- [x] [reference types (done)](https://github.com/WebAssembly/reference-types)
- [ ] [typed function references (not yet)](https://github.com/WebAssembly/function-references)
- [ ] [type imports (not yet)](https://github.com/WebAssembly/proposal-type-imports).

2. After finishing the above requirements, then we can move forward to the GC proposal.

## Appendix

1. GC Proposal: https://github.com/WebAssembly/gc

**Comment by bashor** [comment]
Is there any update about this issue? Does it still target Q4 2022 as defined in [ROADMAP.md](https://github.com/WasmEdge/WasmEdge/blob/master/docs/ROADMAP.md)?

We (in Kotlin) could help you to test it.

**Comment by bashor** [comment]
Ideally, we would like WasmEdge to be able to pass all our compiler tests.
If you want, I can provide some simple binaries.

It looks like we don't need now the support for the "Type Imports and Exports" proposal, I guess, as well as other producers using GC proposal.

**Comment by juntao** [comment]
Yes, we would love to have some binaries to test expected behaviors under this proposal. Thanks!

**Comment by little-willy** [comment]
@bashor Hi, I am working on supporting the GC proposal for WasmEdge. Could you provide some simple binaries for me to do some testing? Thanks!

**Comment by bashor** [comment]
@little-willy Hi! Nice to hear!

You can build a simple example from [these sources](https://github.com/vmware-wasmstack/wasm-languages/tree/main/kotlin/nodejs-hello-world/). 
Check it out and run `./gradlew compileProductionExecutableKotlinWasm` to get binaries in `kotlin/nodejs-hello-world/build/js/packages/nodejs-hello-world-wasm/kotlin/`.

You can notice that there are a bunch of imports, most of them could mocked by dummy implementation especially if don't need to interop with exetrnal world. 

cc @juntao

**Comment by bashor** [comment]
Here are a built binaries: [kotlin-wasm-nodejs-hello.zip](https://github.com/WasmEdge/WasmEdge/files/10396219/kotlin-wasm-nodejs-hello.zip)

**Comment by little-willy** [comment]
@bashor Hi! Thanks for providing the binaries. I just tried running the provided built binaries in the zip file with the interpreter compiled from the latest gc spec repo https://github.com/WebAssembly/gc/tree/main/interpreter. 

Unfortunately, the interpreter cannot execute either the wat or the wasm file. The interpreter reports `syntax error: unexpected token` for the wat, and `decoding error: malformed section id` for the wasm, respectively. I inspected into the wat file, and it seems that the wat generated from the kotlin2wat compiler is using an outdated text and binary format. For example, the heap type `data` has been deprecated in https://github.com/WebAssembly/gc/pull/325/files, while in the generated text format, `ref.null data` is still being used.

The support for gc proposal in WasmEdge is following the latest update in the spec repo. So if the interpreter from the latest gc spec repo cannot execute the generated wat and wasm, the WasmEdge would not be able to execute them either.

Do you have idea on following the latest update from the gc spec repo for the kotlin2wat compiler? Thanks!

**Comment by bashor** [comment]
@little-willy Hi! Thanks for the message.

Binary files are the source for true in our case :). I've looked at the error from the reference interpreter, and it looks like the reference interpreter in the GC proposal repo doesn't support [the tag section introduced by the exception handling proposal](https://github.com/WebAssembly/exception-handling/blob/master/proposals/exception-handling/Exceptions.md#tag-section). I hope you are going to support it as well. Though for some time, we can live without it, e.g., by replacing all throws with unreachable, let me know if you need such an ability in our toolchain.

Speaking about wat files -- some mnemonics/names there might be outdated since we use them only for debugging purposes (just for reading). We need to update them.

In general, we definitely try to keep the toolchain in sync with proposals ([EH](https://github.com/WebAssembly/exception-handling/), [GC](https://github.com/WebAssembly/gc), [TFT](https://github.com/WebAssembly/function-references)), but we find the most pragmatic/important to be compatible with production implementations like V8, binaryen, etc., so we don't use things what not supported there yet. We are following [this document](https://docs.google.com/document/d/14xWenN0lUoHa9TiDJd8yYR8ZKjgOhgO7iEmfrAuA1_M/edit#). You can easily check [the instructions](https://github.com/JetBrains/kotlin/blob/master/wasm/wasm.ir/src/org/jetbrains/kotlin/wasm/ir/Operators.kt) and [types](https://github.com/JetBrains/kotlin/blob/master/wasm/wasm.ir/src/org/jetbrains/kotlin/wasm/ir/Types.kt) we actually use. Specifically, [here are outdated instructions](https://github.com/JetBrains/kotlin/blob/master/wasm/wasm.ir/src/org/jetbrains/kotlin/wasm/ir/Operators.kt#L393-L403) that we are still using to keep compatability.

**Comment by sdeleuze** [comment]
FYI we are now able to run a [Kotlin/Wasm HTTP server via KoWasm on Node.js](https://twitter.com/sdeleuze/status/1629930949944147968) and I would be happy to leverage WasmEdge to run it as soon as it will get GC support. See also my blog post [The huge potential of Kotlin/Wasm](https://seb.deleuze.fr/the-huge-potential-of-kotlin-wasm/) for mote context.

**Comment by juntao** [comment]
Yes, we need to release WasmEdge 0.12 first as it contains several breaking changes. We have GC support in the PR queue, as it requires function reference, and will try to merge then post 0.12. Thanks!

Hope to get it up and running by Barcelona WASM IO. :)

**Comment by sdeleuze** [comment]
Happy to craft a demo for our Wasm I/O talk if that happen.

**Comment by alabulei1** [comment]
Hi @sdeleuze If there is no exception handling proposal, could WasmEdge run the KoWasm project? The GC proposal will be supported after WasmEdge 0.12.0( about after two weeks) is released.

**Comment by sdeleuze** [comment]
Thanks for asking, I am not sure, @bashor could you provide a feedback on this?

**Comment by bashor** [comment]
We can provide a custom build that traps (unreachable) instead of throwing.
If KoWasm and its dependencies don't use exceptions for positive scenarios, it should be enough for experimenting.
Please let me know if you need such a custom build.

**Comment by bashor** [comment]
@alabulei1 @juntao, is there a plan/ETA for exception handling support in WasmEdge?

**Comment by sdeleuze** [comment]
Indeed KoWasm does not throw exceptions for positive scenarios.

@alabulei1 @juntao Timing will be likely too short for Wasm I/O, but I would love to be able to demo Kotlin/Wasm WASI support running on WasmEdge in [my upcoming KotlinConf talk](https://kotlinconf.com/speakers/ce11156d-9a41-4f12-b236-3bdac0ee3a2a) April 13, 14th.

For exception handling, an alternative to the custom Kotlin/Wasm build proposed by @bashor could maybe be to have WasmEdge supporting parsing WebAssembly bytecode with EH enabled, without having to fully implement exception handling. In a nustshell, WasmEdge would not crash when parsing wasm files generated by Kotlin/Wasm and would be fine as long as no exception is thrown. I have created the related #2335 issue.

**Comment by little-willy** [comment]
> We can provide a custom build that traps (unreachable) instead of throwing.
If KoWasm and its dependencies don't use exceptions for positive scenarios, it should be enough for experimenting.
Please let me know if you need such a custom build.

@bashor This will be really helpful. Could you provide me with this binary if possible?

**Comment by skuzmich** [comment]
Custom build that traps (unreachable) instead of throwing:
[kotlin-wasm-gc-no-eh.zip](https://github.com/WasmEdge/WasmEdge/files/10982537/kotlin-wasm-gc-no-eh.zip)

Tested with SpiderMonkey jsshell-mac-2023-03-04-09-52-24-mozilla-central with `--no-wasm-exceptions` flag:
```
$ js --no-wasm-exceptions --wasm-gc --wasm-function-references --module=./index.mjs
exports.add(10, 20) ->  30
exports.sumNumbers(10) ->  55
```

**Comment by little-willy** [comment]
@skuzmich Thanks for providing with the binary!

I just tried running the binary with the [reference interpreter](https://github.com/WebAssembly/gc/tree/master/interpreter) provided by the GC proposal repo. And it fails in a decoding error `decoding error: illegal opcode fb 07`. 

May I ask what's the opcode `0xFB07` stands for? From the GC repo I only see a series of consecutive op nearby stops at `0xfb06| struct.set $t i`

**Comment by skuzmich** [comment]
`fb07` is a `struct.new`
You can find the opcode we use at https://github.com/JetBrains/kotlin/blob/1.8.20/wasm/wasm.ir/src/org/jetbrains/kotlin/wasm/ir/Operators.kt#L352

This encoding can be found in https://docs.google.com/document/d/1DklC3qVuOdLHSXB5UXghM_syCh-4cMinQ50ICiXnK3Q/edit#. It works in V8 and SpiderMonkey. Spec encoding is likely out of sync with the actual implementation prototypes.

**Comment by sdeleuze** [comment]
Hi, as I prepare my Kotlinconf talk, I wanted to know if there is any update or prototype I could demo (even with exception handling disabled).

**Comment by little-willy** [comment]
@sdeleuze I am still working on syncing the latest GC proposal spec as mentioned in the above comment. I am trying to catch up with the kotlin conf. 

I will update the progress and confirm whether we can support running the demo binary provide above or not by April 9th.

**Comment by little-willy** [comment]
@sdeleuze I have tried to pass the loading and validation phase. But now I get stuck at the instantiation phase and get an error about failure to loading `kotlin.captureStackTrace`. To make the linking works, it seems that we should link the function defined in the `index.mjs`.

@juntao Do we now support linking a module defined in js? If so could you tell me how can I do that?

**Comment by juntao** [comment]
> @juntao Do we now support linking a module defined in js? If so could you tell me how can I do that?

Hmm, I am not sure. @L-jasmine can you look into this?

**Comment by L-jasmine** [comment]
@little-willy  I have looked at nodejs-hello-world-wasm.mjs, which defines some additional host functions. We cannot directly link functions defined in JavaScript, so we can only supplement these host functions through APIs/plugins. Fortunately, these missing functions are very simple.

**Comment by bashor** [comment]
> We cannot directly link functions defined in JavaScript, so we can only supplement these host functions through APIs/plugins

@L-jasmine @juntao do you have any plan about supporting it? Just to know.

**Comment by juntao** [comment]
@bashor We will get it done in the next 24 hours. Thanks!

**Comment by juntao** [comment]
Flows summarize

**Comment by L-jasmine** [comment]
```sh
➜  kotlin node --experimental-wasm-modules --experimental-wasm-gc index.mjs

Using experimental Kotlin/Wasm may require enabling experimental features in the target environment.

- Chrome: enable WebAssembly Garbage Collection at chrome://flags/#enable-webassembly-garbage-collection or run the program with the --js-flags=--experimental-wasm-gc command line argument.
- Firefox: enable javascript.options.wasm_function_references and javascript.options.wasm_gc at about:config.
- Edge: run the program with the --js-flags=--experimental-wasm-gc command line argument.
- Node.js: run the program with the --experimental-wasm-gc command line argument.

For more information see https://kotl.in/wasm_help/.

file:///home/csh/workspace/kotlin/index.mjs:172
        const wasmModule = new WebAssembly.Module(wasmBuffer);
                           ^

CompileError: WebAssembly.Module(): Compiling function #57:"kotlin.collections.AbstractMutableCollection$re..." failed: i64.trunc_f32_u[0] expected type f32, found call_ref of type i32 @+52398
    at instantiate (file:///home/csh/workspace/kotlin/index.mjs:172:28)
    at async file:///home/csh/workspace/kotlin/index.mjs:223:18

Node.js v18.15.0
```
@skuzmich 

How can I make it run on Node.js? It seems like there are some issues with the wasm file. Also, I can't seem to get its wat file using Binaryen. Could you please provide the wat file if possible?

**Comment by skuzmich** [comment]
@L-jasmine use node with a newer V8.
For example, https://nodejs.org/download/v8-canary/v20.0.0-v8-canary2022112061c569ba0d/ works:

```
$ node-v20.0.0-v8-canary2022112061c569ba0d-darwin-arm64/bin/node --experimental-wasm-gc ./index.mjs
exports.add(10, 20) ->  30
exports.sumNumbers(10) ->  55
```

> Could you please provide the wat file if possible?

I don't have a working .wat file. I'll attach one I got from Chrome Dev Tools disassembly: [index.wat.zip](https://github.com/WasmEdge/WasmEdge/files/11204272/index.wat.zip). But it doesn't work with binaryen `wasm-as` because of conflicting names.

**Comment by L-jasmine** [comment]
@skuzmich  Hello, there is a value type in `index. wat` that is `structref`, which is defined by what proposal

**Comment by skuzmich** [comment]
@L-jasmine it is a shorthand for `(ref null struct)` in Wasm GC proposal. See: https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md

**Comment by little-willy** [comment]
@skuzmich @sdeleuze Now we have successfully run the provided demo with both `add` and `sumNumbers`.

To make the demo run, in a specially forked branch, we added temporary support for some ops that are marked as deprecated in the GC doc, and disabled some validation and runtime check. Besides, we have to build and register a WasmEdge plugin to mock the link time requirement of the provided demo.

The branch of WasmEdge kernel that support the kotlin demo is at https://github.com/little-willy/WasmEdge/tree/willy/kotlin-gc-demo, while the plugin is at https://github.com/second-state/wasmedge_plugin_rust_sdk/tree/kotlin_gc/examples/plugin/kotlin_demo.

Following is a guide to run the demo. My demo is running on MacOS with M2 chip. Building WasmEdge on MacOS may refer to https://wasmedge.org/book/en/contribute/build_from_src/macos.html.
```bash
# assume that the index.wasm of kotlin demo is located at ${ROOT}
export ROOT=$(pwd)

git clone https://github.com/little-willy/WasmEdge.git -b willy/kotlin-gc-demo
WASMEDGE_ROOT=${ROOT}/WasmEdge

git clone https://github.com/second-state/wasmedge_plugin_rust_sdk.git -b kotlin_gc
WASMEDGE_PLUGIN_ROOT=${ROOT}/wasmedge_plugin_rust_sdk

# build WasmEdge
cd ${WASMEDGE_ROOT}
export LLVM_DIR="$(brew --prefix)/opt/llvm/lib/cmake" #should ensure using llvm@14
export CC=clang
export CXX=clang++
cmake -Bbuild -GNinja .
cmake --build build

# build WasmEdge plugin
cd ${WASMEDGE_PLUGIN_ROOT}/examples/plugin/kotlin_demo
export WASMEDGE_LIB_DIR=${WASMEDGE_ROOT}/build/lib/api/
cargo build

# run the demo
cd ${ROOT}
mkdir plugins
cp ${WASMEDGE_PLUGIN_ROOT}/target/debug/libkotlin_demo.dylib plugins

export DYLD_LIBRARY_PATH=${WASMEDGE_ROOT}/lib/api 
export WASMEDGE_PLUGIN_PATH=${ROOT}/plugins 

# should output 300
${WASMEDGE_ROOT}/build/tools/wasmedge/wasmedge --enable-gc --enable-function-reference index.wasm add 100 200

# should output 55
${WASMEDGE_ROOT}/build/tools/wasmedge/wasmedge --enable-gc --enable-function-reference index.wasm sumNumbers 10

```

**Comment by sdeleuze** [comment]
I was able to build the demo this morning and show it live in my Kotlinconf talk, thanks again for your support and looking forward leveraging that support once refined. https://twitter.com/bashorov/status/1646530280432500736

**Comment by bashor** [comment]
@juntao @little-willy @L-jasmine 
Hi, everyone!

Recently we started working on dedicated support for WASI in our toolchain[^1]. 
We will probably get something to play with within 1-2 months. 

I'm curious about the status and plans regarding the GC proposal in WasmEdge.

[^1]: https://twitter.com/bashorov/status/1674733616151011331

**Comment by juntao** [comment]
Thank you @bashor 

We aim to merge GC support together with a few related proposals, such as function references, in the next month or so. 

Sorry for the delay -- we had extensive refactoring in version 0.12. A lot of code in the GC branch must be updated to be consistent with the refactored main. That takes some work.

**Comment by hydai** [comment]
@q82419 Could you please update this issue since we support the GC proposal and pass the unit tests?

**Comment by q82419** [comment]
GC proposal finished.
