### ISSUE TITLE
failed to run custom build command for `wasmedge-sys v0.5.0`

### ISSUE THREAD

**Issue by faroukianoxide** [WasmEdge/WasmEdge#1500]
## Description

I am trying to embed the WasmEdge runtime in a Rust project that uses `actix-web`.

When running `cargo build` with `wasmedge-sys v0.5.0` as dependency, the build terminates on building `wasmedge-sys` and throws the following error:

```shell

failed to run custom build command for `wasmedge-sys v0.5.0`

Caused by:
  process didn't exit successfully: `C:\my\project\path\target\debug\build\wasmedge-sys-9e920e32a1f7ea85\build-script-build` (exit code: 101)
  --- stdout
  cargo:warning=[wasmedge-sys] not_standalone
  cargo:warning=[wasmedge-sys] TARGET_OS: windows
  cargo:warning=[wasmedge-sys] git init output: Output { status: ExitStatus(ExitStatus(0)), stdout: "Initialized empty Git repository in C:/my/project/path/target/debug/build/wasmedge-sys-56ae5bf345a3a2cf/out/wasmedge/.git/\n", stderr: "" }

cargo:warning=[wasmedge-sys] git remote add output: Output { status: ExitStatus(ExitStatus(0)), stdout: "", stderr: "" }
  cargo:warning=[wasmedge-sys] git fetch output: Output { status: ExitStatus(ExitStatus(0)), stdout: "", stderr: "From https://github.com/WasmEdge/WasmEdge\n * branch              HEAD       -> FETCH_HEAD\n" }
  cargo:warning=[wasmedge-sys] git checkout output: Output { status: ExitStatus(ExitStatus(0)), stdout: "", stderr: "Note: switching to 'FETCH_HEAD'.\n\nYou are in 'detached HEAD' state. You can look around, make experimental\nchanges and commit them, and you can discard any commits you make in this\nstate without impacting any branches by switching back to a branch.\n\nIf you want to create a new branch to retain commits you create, you may\ndo so (now or later) by using -c with the switch command. Example:\n\n  git switch -c <new-branch-name>\n\nOr undo this operation with:\n\n  git switch -\n\nTurn off this advice by setting config variable advice.detachedHead to false\n\nHEAD is now at 0c36dbe1 [Changelog] Update the changelog for the 0.10.0 release.\n" }

  --- stderr
  thread 'main' panicked at 'assertion failed: inc_dir.exists()', C:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\build.rs:426:5  
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

## Environment

- Hardware Architecture: x86/64
- Operating system: Windows 11

I have this in the dependencies in my `Cargo.toml` file:

```toml
[dependencies]
actix-web = "4"
wasmedge-sys = "0.5.0" # the same error occurs with 0.3.0 as well
wasmedge-types = "0.1.1"

```

## Steps to Reproduce

1. `cargo new <project-name>`
2. Add the above to your cargo dependencies
3. run `cargo build`

Can anyone help me with this? -- please

**Comment by faroukianoxide** [comment]
Thank you so much @apepkuss for your reply.

So I tried the first option (the second didn't work) and now it's demanding that I set the path to find `clang.dll` and `libclang.dll`. 
```shell
thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.59.2\src/lib.rs:2144:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I guess I have to grab and build `clang` then. I will let you know how it goes.
But I am just curious, is this a normal/expected behavior because none of these was mentioned in the `WasmEdge`  Rust doc?

Thanks again @apepkuss

**Comment by apepkuss** [comment]
Hi @faroukianoxide 

Thanks for your feedback, and sorry for the inconvenience. We also noticed the issue you mentioned. Our [WasmEdge Book](https://wasmedge.org/book/en/index.html) will add a specific section for solving the issue ASAP. 

@hydai Could you please help with the `dll` issues? It seems the issues happened while compiling `WasmEdge`.

**Comment by hydai** [comment]
If you have to build from source on Windows platform, please refer to our build workflow: https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/build.yml#L293-L356

**Comment by faroukianoxide** [comment]
`clang` issue now resolved (thanks), but now I have this:

```shell

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ImportObjectGetModuleName` in module `ffi`
    --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\import_obj.rs:44:38
     |
44   |           let raw_name = unsafe { ffi::WasmEdge_ImportObjectGetModuleName(self.inner.0 as *const _) };
     |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_ImportTypeGetModuleName`
     |
    ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:1391:5
     |
1391 | /     pub fn WasmEdge_ImportTypeGetModuleName(
1392 | |         Cxt: *const WasmEdge_ImportTypeContext,
1393 | |     ) -> WasmEdge_String;
     | |_________________________- similarly named function `WasmEdge_ImportTypeGetModuleName` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceGetModuleName` in module `ffi`
    --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:24:34
     |
24   |           let name = unsafe { ffi::WasmEdge_ModuleInstanceGetModuleName(self.inner.0 as *const _) };
     |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_TableInstanceGetTableType`
     |
    ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:2580:5
     |
2580 | /     pub fn WasmEdge_TableInstanceGetTableType(
2581 | |         Cxt: *const WasmEdge_TableInstanceContext,
2582 | |     ) -> *const WasmEdge_TableTypeContext;
     | |__________________________________________- similarly named function `WasmEdge_TableInstanceGetTableType` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceFindFunction` in module `ffi`
  --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:46:18
   |
46 |             ffi::WasmEdge_ModuleInstanceFindFunction(
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceFindTable` in module `ffi`
  --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:78:18
   |
78 |             ffi::WasmEdge_ModuleInstanceFindTable(
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceFindMemory` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:108:18
    |
108 |             ffi::WasmEdge_ModuleInstanceFindMemory(
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceFindGlobal` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:138:18
    |
138 |             ffi::WasmEdge_ModuleInstanceFindGlobal(
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceListFunctionLength` in module `ffi`
    --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:157:23
     |
157  |         unsafe { ffi::WasmEdge_ModuleInstanceListFunctionLength(self.inner.0) }
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_StoreListFunctionLength`
     |
    ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:2053:5
     |
2053 |     pub fn WasmEdge_StoreListFunctionLength(Cxt: *const WasmEdge_StoreContext) -> u32;
     |     ---------------------------------------------------------------------------------- similarly named function `WasmEdge_StoreListFunctionLength` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceListFunction` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:167:26
    |
167 |                     ffi::WasmEdge_ModuleInstanceListFunction(
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceListTableLength` in module `ffi`
    --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:187:23
     |
187  |         unsafe { ffi::WasmEdge_ModuleInstanceListTableLength(self.inner.0) }
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_StoreListTableLength`
     |
    ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:2126:5
     |
2126 |     pub fn WasmEdge_StoreListTableLength(Cxt: *const WasmEdge_StoreContext) -> u32;
     |     ------------------------------------------------------------------------------- similarly named function `WasmEdge_StoreListTableLength` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceListTable` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:197:26
    |
197 |                     ffi::WasmEdge_ModuleInstanceListTable(
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceListMemoryLength` in module `ffi`
    --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:217:23
     |
217  |         unsafe { ffi::WasmEdge_ModuleInstanceListMemoryLength(self.inner.0) }
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_StoreListMemoryLength`
     |
    ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:2199:5
     |
2199 |     pub fn WasmEdge_StoreListMemoryLength(Cxt: *const WasmEdge_StoreContext) -> u32;
     |     -------------------------------------------------------------------------------- similarly named function `WasmEdge_StoreListMemoryLength` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceListMemory` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:227:26
    |
227 |                     ffi::WasmEdge_ModuleInstanceListMemory(
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceListGlobalLength` in module `ffi`
    --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:247:23
     |
247  |         unsafe { ffi::WasmEdge_ModuleInstanceListGlobalLength(self.inner.0) }
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_StoreListGlobalLength`
     |
    ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:2272:5
     |
2272 |     pub fn WasmEdge_StoreListGlobalLength(Cxt: *const WasmEdge_StoreContext) -> u32;
     |     -------------------------------------------------------------------------------- similarly named function `WasmEdge_StoreListGlobalLength` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceListGlobal` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:257:26
    |
257 |                     ffi::WasmEdge_ModuleInstanceListGlobal(
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0412]: cannot find type `WasmEdge_ModuleInstanceContext` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\instance\module.rs:277:56
    |
277 | pub(crate) struct InnerInstance(pub(crate) *const ffi::WasmEdge_ModuleInstanceContext);
    |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `WasmEdge_TableInstanceContext`
    |
   ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:445:1
    |
445 | pub struct WasmEdge_TableInstanceContext {
    | ---------------------------------------- similarly named struct `WasmEdge_TableInstanceContext` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_StoreGetActiveModule` in module `ffi`
    --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\store.rs:618:33
     |
618  |           let ctx = unsafe { ffi::WasmEdge_StoreGetActiveModule(self.inner.0) };
     |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_StoreListModule`
     |
    ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:2358:5
     |
2358 | /     pub fn WasmEdge_StoreListModule(
2359 | |         Cxt: *const WasmEdge_StoreContext,
2360 | |         Names: *mut WasmEdge_String,
2361 | |         Len: u32,
2362 | |     ) -> u32;
     | |_____________- similarly named function `WasmEdge_StoreListModule` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_StoreFindModule` in module `ffi`
    --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\store.rs:639:33
     |
639  |           let ctx = unsafe { ffi::WasmEdge_StoreFindModule(self.inner.0, mod_name.as_raw()) };
     |                                   ^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_StoreListModule`
     |
    ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:2358:5
     |
2358 | /     pub fn WasmEdge_StoreListModule(
2359 | |         Cxt: *const WasmEdge_StoreContext,
2360 | |         Names: *mut WasmEdge_String,
2361 | |         Len: u32,
2362 | |     ) -> u32;
     | |_____________- similarly named function `WasmEdge_StoreListModule` defined here

error[E0425]: cannot find value `WasmEdge_ValType_None` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:107:35
    |
107 |             ValType::None => ffi::WasmEdge_ValType_None,
    |                                   ^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `WasmEdge_ValType_F32`
    |
   ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:174:1
    |
174 | pub const WasmEdge_ValType_F32: WasmEdge_ValType = 125;
    | ------------------------------------------------------- similarly named constant `WasmEdge_ValType_F32` defined here

error[E0531]: cannot find unit struct, unit variant or constant `WasmEdge_ValType_None` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:121:18
    |
121 |             ffi::WasmEdge_ValType_None => ValType::None,
    |                  ^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `WasmEdge_ValType_F32`
    |
   ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:174:1
    |
174 | pub const WasmEdge_ValType_F32: WasmEdge_ValType = 125;
    | ------------------------------------------------------- similarly named constant `WasmEdge_ValType_F32` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ValueGetFuncRef` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:477:36
    |
477 |                     let ctx = ffi::WasmEdge_ValueGetFuncRef(self.ctx);
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_ValueGenFuncRef`
    |
   ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:569:5
    |
569 |     pub fn WasmEdge_ValueGenFuncRef(Index: u32) -> WasmEdge_Value;
    |     -------------------------------------------------------------- similarly named function `WasmEdge_ValueGenFuncRef` defined here

error[E0531]: cannot find unit struct, unit variant or constant `WasmEdge_ValType_None` in module `ffi`
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:552:18
    |
552 |             ffi::WasmEdge_ValType_None => Self {
    |                  ^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `WasmEdge_ValType_F32`
    |
   ::: C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-56ae5bf345a3a2cf\out/wasmedge.rs:174:1
    |
174 | pub const WasmEdge_ValType_F32: WasmEdge_ValType = 125;
    | ------------------------------------------------------- similarly named constant `WasmEdge_ValType_F32` defined here

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:160:10
    |
160 |     O0 = ffi::WasmEdge_CompilerOptimizationLevel_O0,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:163:10
    |
163 |     O1 = ffi::WasmEdge_CompilerOptimizationLevel_O1,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:167:10
    |
167 |     O2 = ffi::WasmEdge_CompilerOptimizationLevel_O2,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:170:10
    |
170 |     O3 = ffi::WasmEdge_CompilerOptimizationLevel_O3,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:174:10
    |
174 |     Os = ffi::WasmEdge_CompilerOptimizationLevel_Os,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:177:10
    |
177 |     Oz = ffi::WasmEdge_CompilerOptimizationLevel_Oz,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:198:14
    |
198 |     Native = ffi::WasmEdge_CompilerOutputFormat_Native,
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:201:12
    |
201 |     Wasm = ffi::WasmEdge_CompilerOutputFormat_Wasm,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:243:16
    |
243 |     Function = ffi::WasmEdge_ExternalType_Function,
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:244:13
    |
244 |     Table = ffi::WasmEdge_ExternalType_Table,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:245:14
    |
245 |     Memory = ffi::WasmEdge_ExternalType_Memory,
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

error[E0308]: mismatched types
   --> C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.5.0\src\types.rs:246:14
    |
246 |     Global = ffi::WasmEdge_ExternalType_Global,
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `i32`

```
Even after pulling fresh `v0.5.0` code into my `cargo` registry. I should also mention that I am nothing close to a `rust` expert. 
Thanks.

**Comment by apepkuss** [comment]
@faroukianoxide 

I reproduced the issue with `wasmedge-sys v0.5.0` and `wasmedge v0.9.1`. According to our investigation, `wasmedge-sys v0.5.0` is based on the APIs of `wasmedge` between `v0.9.1` and `v0.10.0`. So a feasible solution to the issue is to build a wasmedge from `commit 7e791fbc`, and replace the old one with the new one. Another way is that today we released [wasmedge v0.10.0](https://github.com/WasmEdge/WasmEdge/releases/tag/0.10.0) and [wasmedge-sys v0.7.0](https://crates.io/crates/wasmedge-sys) (also [rustdoc](https://wasmedge.github.io/WasmEdge/wasmedge_sys/)), which can work together correctly. You can upgrade to the new release. One more thing, we also released [wasmedge-sdk v0.1.0](https://crates.io/crates/wasmedge-sdk)(its [rustdoc](https://wasmedge.github.io/WasmEdge/wasmedge_sdk/)), which provides the high-level Rust APIs for `WasmEdge`. Personally, I suggest you try it. Of course, we also need your feedback on it. Thank you very much!

**Comment by hydai** [comment]
@apepkuss Since there is not a pre-built release for `wasmedge-sys v0.5.0`, should we yank this version and make users to use the next release?

**Comment by faroukianoxide** [comment]
So I upgraged `wasmedge-sys` to `v0.7.0`  and `wasmedge` to `v0.10.0` as @apepkuss suggested. Things seemed to go a bit better than now except that I encountered this:

```shell
error: failed to run custom build command for `wasmedge-sys v0.7.0`

Caused by:
  process didn't exit successfully: `C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-1c84e13f0b485641\build-script-build` (exit code: 101)
  --- stdout
  cargo:warning=[wasmedge-sys] Use WASMEDGE_INCLUDE_DIR: "C:\\Program Files\\WasmEdge\\include"
  cargo:warning=[wasmedge-sys] Use WASMEDGE_LIB_DIR: "C:\\Program Files\\WasmEdge\\lib"

  --- stderr
  C:\Program Files\WasmEdge\include\wasmedge/enum_configure.h:59:10: fatal error: 'enum.inc' file not found
  C:\Program Files\WasmEdge\include\wasmedge/enum_configure.h:59:10: fatal error: 'enum.inc' file not found, err: true
  thread 'main' panicked at 'failed to generate bindings: ()', C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.7.0\build.rs:51:10
```
 Any suggestions, please?

**Comment by apepkuss** [comment]
@hydai I just worry that some guys are building up their apps based on this version in the `standalone` mode, for example, `substrate-wasmedge`. `wasmedge-sys v0.5.0` can work in the `standalone` mode correctly on Linux and macOS, so considering these users, keeping `v0.5.0` could be reasonable. But the issues above are a good lesson for us. I believe that a CI job against the `standalone` mode on the Windows platform should be added to the current `bindings-rust` workflow. That would guarantee a better quality on the Windows platform.

**Comment by apepkuss** [comment]
> So I upgraged `wasmedge-sys` to `v0.7.0` and `wasmedge` to `v0.10.0` as @apepkuss suggested. Things seemed to have gone a bit better, except that I encountered this:
> 
> ```shell
> error: failed to run custom build command for `wasmedge-sys v0.7.0`
> 
> Caused by:
>   process didn't exit successfully: `C:\Users\Farouk\Desktop\exprj\more recent\werust\target\debug\build\wasmedge-sys-1c84e13f0b485641\build-script-build` (exit code: 101)
>   --- stdout
>   cargo:warning=[wasmedge-sys] Use WASMEDGE_INCLUDE_DIR: "C:\\Program Files\\WasmEdge\\include"
>   cargo:warning=[wasmedge-sys] Use WASMEDGE_LIB_DIR: "C:\\Program Files\\WasmEdge\\lib"
> 
>   --- stderr
>   C:\Program Files\WasmEdge\include\wasmedge/enum_configure.h:59:10: fatal error: 'enum.inc' file not found
>   C:\Program Files\WasmEdge\include\wasmedge/enum_configure.h:59:10: fatal error: 'enum.inc' file not found, err: true
>   thread 'main' panicked at 'failed to generate bindings: ()', C:\Users\Farouk\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmedge-sys-0.7.0\build.rs:51:10
> ```
> 
> Any suggestions, please?

@hydai Could you help with this issue? It seems a failure was caused during the compilation of `WasmEdge`. It behaves so weirdly on the Windows platform.

**Comment by hydai** [comment]
I will say that we should show a warning message when people are using `wasmedge-sys` on the Windows platform currently. Unless we create a workflow to cover the `wasmedge-sys` on the windows platform.

The reasons are:
1. Most of the WASI functions are not implemented on the Windows platform. Tracking issue: https://github.com/WasmEdge/WasmEdge/issues/1477
2. There is no workflow for testing the rust-related crates on the Windows platform. Tracking issue: TBD
