### ISSUE TITLE
Cannot run examples in "wasmedge_http_req"

### ISSUE THREAD

**Issue by Ren-ZY** [WasmEdge/WasmEdge#1633]
When I try to run examples (get.rs) in `wasmedge_http_req`, it turns out to be a panic as follow:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IO(Error { kind: Unsupported, message: "operation not supported on this platform" })', examples/get.rs:5:75
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2022-07-08 19:38:35.168] [error]     execution failed: unreachable, Code: 0x89
[2022-07-08 19:38:35.168] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x00051592
[2022-07-08 19:38:35.168] [error]     When executing function name: "_start"
```

**Comment by juntao** [comment]
May I ask which OS are you running?

**Comment by Ren-ZY** [comment]
I just compile the source code into **.wasm** format using the command **cargo build --examples --target wasm32-wasi**
and try to run the binary using **wasmedge get.wasm**. Then it shows the error.
My OS is Linux (Ubuntu 18.04)

**Comment by alabulei1** [comment]
https://github.com/second-state/wasmedge_http_req/pull/4 solved this problem. Please try again.

Let us know if this works.

**Comment by Ren-ZY** [comment]
It works.

**Comment by shijunti19** [comment]
@Ren-ZY Windows 10 and Centos8 did not solve this problem

```
root@xiaolu http_server]#  wasmedge ./target/wasm32-wasi/release/http_server.wasm
thread 'main' panicked at 'error binding to 0.0.0.0:8080: error creating server listener: unsupported', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper_wasi-0.15.2/src/server/server.rs:81:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-07-07 08:14:44.857] [error] execution failed: unreachable, Code: 0x89
[2023-07-07 08:14:44.857] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x000c015e
[2023-07-07 08:14:44.857] [error]     When executing function name: "_start"
```
