### ISSUE TITLE
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

### ISSUE THREAD

**Issue by loredanacirstea** [WasmEdge/WasmEdge#2400]
## Description

Since adding support for executing AOT compiled modules, with wasmedge in Go, I have tests that fail with 
```
signal 16 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag
```

### Current State

When running the project's tests, the above error obfuscates any test failures. Some tests that passed before, now fail with the above error. Some tests are flaky - sometimes they pass, and other times I get this error.

### Expected

Not having this `signal handler` error obfuscate the real failure.

What I've found is:

https://pkg.go.dev/os/signal#hdr-Go_programs_that_use_cgo_or_SWIG
> If the non-Go code installs any signal handlers, it must use the SA_ONSTACK flag with sigaction. Failing to do so is likely to cause the program to crash if the signal is received. Go programs routinely run with a limited stack, and therefore set up an alternate signal stack.

This might be solved by `Action.sa_flags = SA_SIGINFO | SA_ONSTACK;` here https://github.com/WasmEdge/WasmEdge/blob/4c37361fa44a6c2860b922ef3af3af594bb760c8/lib/system/fault.cpp#L129

## Environment

- Hardware Architecture: (e.g. x86\_64 or aarch64): arm64
- Operating system: (e.g. Ubuntu 20.04 or CentOS 7.6): macOS 13.3.1
- WasmEdge 0.11.2

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version:
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`)
- Boost version:

**Comment by loredanacirstea** [comment]
Update: I tested the same project setup on Ubuntu 22.04 and on MacOS 12.6.3 (x86_64) and all tests pass as expected, without the `signal handler` error.

So the above `signal handler` problem only happens on the MacOS M1 computer. I tested on a different MacOS M1 (13.4 Beta) and the `signal handler` problem was present.

**Comment by hydai** [comment]
Hi @loredanacirstea 
Thanks for this. Could you reproduce the same error now? Or do we need to add the `sa_flags` for the current go SDK to avoid this issue?

**Comment by loredanacirstea** [comment]
The same issue persists with:
macOS 14.0
WasmEdge 0.13.4

Full error when running `go test` is
```
signal 16 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw({0x1041284e8?, 0x14000088000?})
	/usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0x14000fa3550 sp=0x14000fa3520 pc=0x1029c3a50
runtime.sigNotOnStack(0x10)
	/usr/local/go/src/runtime/signal_unix.go:1020 +0x5c fp=0x14000fa3570 sp=0x14000fa3550 pc=0x1029db46c
runtime.adjustSignalStack(0x10, 0x14000100480, 0x14000fa3618)
	/usr/local/go/src/runtime/signal_unix.go:581 +0x250 fp=0x14000fa35e0 sp=0x14000fa3570 pc=0x1029da390
runtime.sigtrampgo(0x10, 0x14000fa3780, 0x14000fa37e8)
	/usr/local/go/src/runtime/signal_unix.go:469 +0x174 fp=0x14000fa3660 sp=0x14000fa35e0 pc=0x1029d9fe4
runtime.sigtrampgo(0x10, 0x14000fa3780, 0x14000fa37e8)
	<autogenerated>:1 +0x1c fp=0x14000fa3690 sp=0x14000fa3660 pc=0x1029f97ac
runtime.sigtramp()
	/usr/local/go/src/runtime/sys_darwin_arm64.s:227 +0x4c fp=0x14000fa3750 sp=0x14000fa3690 pc=0x1029f8c2c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000096fe0 sp=0x14000096fe0 pc=0x1029f7ed4

goroutine 1 [chan receive]:
runtime.gopark(0x1400123fa18?, 0x102aa2ae8?, 0x78?, 0xfa?, 0x102997a5c?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14001a8f9f0 sp=0x14001a8f9d0 pc=0x1029c6394
runtime.chanrecv(0x1400009a620, 0x1400123faff, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x454 fp=0x14001a8fa80 sp=0x14001a8f9f0 pc=0x102990e24
runtime.chanrecv1(0x1040aec2e?, 0x1040aec2e?)
	/usr/local/go/src/runtime/chan.go:442 +0x14 fp=0x14001a8fab0 sp=0x14001a8fa80 pc=0x102990994
testing.(*T).Run(0x14001243a00, {0x1040aec2e?, 0x2396adaf7a51?}, 0x105377310)
	/usr/local/go/src/testing/testing.go:1494 +0x314 fp=0x14001a8fb50 sp=0x14001a8fab0 pc=0x102aa7c44
testing.runTests.func1(0x0?)
	/usr/local/go/src/testing/testing.go:1846 +0x70 fp=0x14001a8fba0 sp=0x14001a8fb50 pc=0x102aa9a30
testing.tRunner(0x14001243a00, 0x1400123fcb8)
	/usr/local/go/src/testing/testing.go:1446 +0x10c fp=0x14001a8fbf0 sp=0x14001a8fba0 pc=0x102aa6fac
testing.runTests(0x14000e14b40?, {0x106371ec0, 0x3, 0x3}, {0xaa00000000000000?, 0xaa3dd48e320fd929?, 0x1086f6a40?})
	/usr/local/go/src/testing/testing.go:1844 +0x3f0 fp=0x14001a8fce0 sp=0x14001a8fbf0 pc=0x102aa98f0
testing.(*M).Run(0x14000e14b40)
	/usr/local/go/src/testing/testing.go:1726 +0x4f0 fp=0x14001a8fee0 sp=0x14001a8fce0 pc=0x102aa8560
main.main()
	_testmain.go:53 +0x1d0 fp=0x14001a8ff70 sp=0x14001a8fee0 pc=0x104080dc0
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x24c fp=0x14001a8ffd0 sp=0x14001a8ff70 pc=0x1029c5fcc
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14001a8ffd0 sp=0x14001a8ffd0 pc=0x1029f7ed4

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000084fa0 sp=0x14000084f80 pc=0x1029c6394
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xac fp=0x14000084fd0 sp=0x14000084fa0 pc=0x1029c622c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000084fd0 sp=0x14000084fd0 pc=0x1029f7ed4
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000085770 sp=0x14000085750 pc=0x1029c6394
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:297 +0x10c fp=0x140000857b0 sp=0x14000085770 pc=0x1029b10fc
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x140000857d0 sp=0x140000857b0 pc=0x1029a5658
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000857d0 sp=0x140000857d0 pc=0x1029f7ed4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x74

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x140000ae000?, 0x104ecd100?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000085f50 sp=0x14000085f30 pc=0x1029c6394
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x1086fc560)
	/usr/local/go/src/runtime/mgcscavenge.go:389 +0x5c fp=0x14000085f80 sp=0x14000085f50 pc=0x1029af04c
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:622 +0xac fp=0x14000085fb0 sp=0x14000085f80 pc=0x1029af65c
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x14000085fd0 sp=0x14000085fb0 pc=0x1029a55f8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000085fd0 sp=0x14000085fd0 pc=0x1029f7ed4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xb8

goroutine 18 [finalizer wait]:
runtime.gopark(0x1086fe060?, 0x400000?, 0x0?, 0x0?, 0x1029a5abc?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000084580 sp=0x14000084560 pc=0x1029c6394
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x120 fp=0x140000847d0 sp=0x14000084580 pc=0x1029a4880
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000847d0 sp=0x140000847d0 pc=0x1029f7ed4
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x84

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000080740 sp=0x14000080720 pc=0x1029c6394
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140000807d0 sp=0x14000080740 pc=0x1029a7a3c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000807d0 sp=0x140000807d0 pc=0x1029f7ed4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x2396c58c1125?, 0x3?, 0xae?, 0x54?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000112740 sp=0x14000112720 pc=0x1029c6394
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140001127d0 sp=0x14000112740 pc=0x1029a7a3c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001127d0 sp=0x140001127d0 pc=0x1029f7ed4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x2396c58c10a8?, 0x1?, 0x75?, 0x18?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000080f40 sp=0x14000080f20 pc=0x1029c6394
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000080fd0 sp=0x14000080f40 pc=0x1029a7a3c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000080fd0 sp=0x14000080fd0 pc=0x1029f7ed4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x2396c58c0e8b?, 0x1?, 0x3?, 0xad?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000081740 sp=0x14000081720 pc=0x1029c6394
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140000817d0 sp=0x14000081740 pc=0x1029a7a3c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000817d0 sp=0x140000817d0 pc=0x1029f7ed4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x2396c58c5216?, 0x3?, 0xb2?, 0x13?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000086740 sp=0x14000086720 pc=0x1029c6394
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140000867d0 sp=0x14000086740 pc=0x1029a7a3c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000867d0 sp=0x140000867d0 pc=0x1029f7ed4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x1087341c0?, 0x1?, 0x3?, 0xad?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000112f40 sp=0x14000112f20 pc=0x1029c6394
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000112fd0 sp=0x14000112f40 pc=0x1029a7a3c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000112fd0 sp=0x14000112fd0 pc=0x1029f7ed4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x1087341c0?, 0x1?, 0x4f?, 0x4d?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000086f40 sp=0x14000086f20 pc=0x1029c6394
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000086fd0 sp=0x14000086f40 pc=0x1029a7a3c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000086fd0 sp=0x14000086fd0 pc=0x1029f7ed4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x2396c58c0ede?, 0x1?, 0x69?, 0xaa?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000081f40 sp=0x14000081f20 pc=0x1029c6394
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000081fd0 sp=0x14000081f40 pc=0x1029a7a3c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000081fd0 sp=0x14000081fd0 pc=0x1029f7ed4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x2396c58c1055?, 0x1?, 0x87?, 0x97?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000087740 sp=0x14000087720 pc=0x1029c6394
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140000877d0 sp=0x14000087740 pc=0x1029a7a3c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000877d0 sp=0x140000877d0 pc=0x1029f7ed4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x2396c58bdd63?, 0x3?, 0xc?, 0x76?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000113740 sp=0x14000113720 pc=0x1029c6394
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140001137d0 sp=0x14000113740 pc=0x1029a7a3c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001137d0 sp=0x140001137d0 pc=0x1029f7ed4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 24 [select]:
runtime.gopark(0x14000114f78?, 0x3?, 0x0?, 0x0?, 0x14000114f62?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000114e00 sp=0x14000114de0 pc=0x1029c6394
runtime.selectgo(0x14000114f78, 0x14000114f5c, 0x14000231f80?, 0x0, 0x14000114f88?, 0x1)
	/usr/local/go/src/runtime/select.go:328 +0x688 fp=0x14000114f20 sp=0x14000114e00 pc=0x1029d6ca8
go.opencensus.io/stats/view.(*worker).start(0x14000231f80)
	/Users/user/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x88 fp=0x14000114fb0 sp=0x14000114f20 pc=0x103bf0948
go.opencensus.io/stats/view.init.0.func1()
	/Users/user/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x28 fp=0x14000114fd0 sp=0x14000114fb0 pc=0x103befc78
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000114fd0 sp=0x14000114fd0 pc=0x1029f7ed4
created by go.opencensus.io/stats/view.init.0
	/Users/user/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0xa4

goroutine 9 [chan receive]:
runtime.gopark(0x14000d05b88?, 0x102aa2ae8?, 0xe8?, 0x5b?, 0x102997a5c?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x140010ebb60 sp=0x140010ebb40 pc=0x1029c6394
runtime.chanrecv(0x1400009ae70, 0x14000d05c6f, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x454 fp=0x140010ebbf0 sp=0x140010ebb60 pc=0x102990e24
runtime.chanrecv1(0x140001a67c0?, 0x140001a67c0?)
	/usr/local/go/src/runtime/chan.go:442 +0x14 fp=0x140010ebc20 sp=0x140010ebbf0 pc=0x102990994
testing.(*T).Run(0x14001243ba0, {0x104f6f2cb?, 0x14001243ba0?}, 0x1400040d680)
	/usr/local/go/src/testing/testing.go:1494 +0x314 fp=0x140010ebcc0 sp=0x140010ebc20 pc=0x102aa7c44
github.com/stretchr/testify/suite.runTests({0x1053b3770, 0x14001243ba0}, {0x14000265800?, 0x43, 0x80})
	/Users/user/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:242 +0x130 fp=0x140010ebd30 sp=0x140010ebcc0 pc=0x104021700
github.com/stretchr/testify/suite.Run(0x14001243ba0, {0x10539c920, 0x14000518af0})
	/Users/user/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:215 +0x604 fp=0x140010ebf10 sp=0x140010ebd30 pc=0x104020ca4
mythos/v1/x/wasmx/keeper_test.TestKeeperTestSuite(0x0?)
	/Users/user/dev/blockchain/wasmx/x/wasmx/keeper/keeper_test.go:93 +0x6c fp=0x140010ebf60 sp=0x140010ebf10 pc=0x10406c86c
testing.tRunner(0x14001243ba0, 0x105377310)
	/usr/local/go/src/testing/testing.go:1446 +0x10c fp=0x140010ebfb0 sp=0x140010ebf60 pc=0x102aa6fac
testing.(*T).Run.func1()
	/usr/local/go/src/testing/testing.go:1493 +0x2c fp=0x140010ebfd0 sp=0x140010ebfb0 pc=0x102aa7cec
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140010ebfd0 sp=0x140010ebfd0 pc=0x1029f7ed4
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x300

goroutine 10 [running]:
	goroutine running on other thread; stack unavailable
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x300
FAIL	mythos/v1/x/wasmx/keeper	1.520s
FAIL
```

**Comment by hydai** [comment]
Hi @loredanacirstea 
Thanks for the confirmation. I plan to fix this in the 0.14.0 release. We will let you know once it has been fixed.
