### ISSUE TITLE
Installer failing on Ubuntu 22.04 aarch64

### ISSUE THREAD

**Issue by dyasny** [WasmEdge/WasmEdge#2622]
## Description

Installer is failing on a fresh Ubuntu 22.04 aarch64 on AWS

### Current State

Installer is run using the standard shell:

```
ubuntu@myvm$ curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash

Using Python: /usr/bin/python3 
Compatible with current configuration
Running Uninstaller
ls: cannot access '/home/ubuntu/.wasmedge': No such file or directory
WARNING - SHELL variable not found. Using bash as SHELL
shell configuration updated
Downloading WasmEdge
Traceback (most recent call last):
  File "<stdin>", line 1584, in <module>
  File "<stdin>", line 1367, in main
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

I tried to dig in a bit, downloaded the python installer script and ran it with -D

```
ubuntu@myvm:~$ python3 ./install.py -D
DEBUG   - Python Version: sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)
DEBUG   - Compat object: Platform:Linux
Machine:aarch64
Version:0.12.1
Extensions:[]
Dist:ubuntu20.04

DEBUG   - Temp path: /tmp/wasmedge.1911
DEBUG   - CLI Args:
DEBUG   - Namespace(extensions=[], version='0.12.1', loglevel=10, path='/home/ubuntu/.wasmedge', remove_old=None, uninstall_script_tag='0.12.1', plugins=[], tf_version='0.12.1', tf_deps_version='0.12.1', tf_tools_version='0.12.1', image_version='0.12.1', platform='Linux', machine='aarch64', dist=None)
Compatible with current configuration
DEBUG   - Tensorflow release pkg: ubuntu20.04_aarch64.tar.gz
DEBUG   - Image release pkg: ubuntu20.04_aarch64.tar.gz
Running Uninstaller
ls: cannot access '/home/ubuntu/.wasmedge': No such file or directory
DEBUG   - No root permissions.
Installation path found at /home/ubuntu/.wasmedge
Removing /home/ubuntu/.wasmedge/env
Removing _ERROR_ : Found 1 file(s) only
Removing /home/ubuntu/.wasmedge/plugin
Removing /home/ubuntu/.wasmedge
Removing /home/ubuntu/.wasmedge
DEBUG   - CONST_env_path: /home/ubuntu/.wasmedge/env
DEBUG   - CONST_release_pkg: manylinux2014_aarch64.tar.gz
DEBUG   - CONST_ipkg: WasmEdge-0.12.1-Linux
DEBUG   - CONST_lib_ext: .so
DEBUG   - CONST_urls: {'WasmEdge': 'https://github.com/WasmEdge/WasmEdge/releases/download/0.12.1/WasmEdge-0.12.1-ubuntu20.04_aarch64.tar.gz', 'WasmEdge_Uninstaller': 'https://raw.githubusercontent.com/WasmEdge/WasmEdge/0.12.1/utils/uninstall.sh', 'image': 'https://github.com/second-state/WasmEdge-image/releases/download/0.12.1/WasmEdge-image-0.12.1-ubuntu20.04_aarch64.tar.gz', 'tensorflow_deps': 'https://github.com/second-state/WasmEdge-tensorflow-deps/releases/download/0.12.1/WasmEdge-tensorflow-deps-TF-0.12.1-manylinux2014_aarch64.tar.gz', 'tensorflow_lite_deps': 'https://github.com/second-state/WasmEdge-tensorflow-deps/releases/download/0.12.1/WasmEdge-tensorflow-deps-TFLite-0.12.1-manylinux2014_aarch64.tar.gz', 'tensorflow': 'https://github.com/second-state/WasmEdge-tensorflow/releases/download/0.12.1/WasmEdge-tensorflow-0.12.1-ubuntu20.04_aarch64.tar.gz', 'tensorflow_lite': 'https://github.com/second-state/WasmEdge-tensorflow/releases/download/0.12.1/WasmEdge-tensorflowlite-0.12.1-ubuntu20.04_aarch64.tar.gz', 'tensorflow_tools': 'https://github.com/second-state/WasmEdge-tensorflow-tools/releases/download/0.12.1/WasmEdge-tensorflow-tools-0.12.1-manylinux2014_aarch64.tar.gz'}
DEBUG   - CONST_lib_dir: lib
WARNING - SHELL variable not found. Using bash as SHELL
shell configuration updated
DEBUG   - CONST_shell_profile: /home/ubuntu/.bash_profile
DEBUG   - CONST_shell_config: /home/ubuntu/.bashrc
Downloading WasmEdge
Traceback (most recent call last):
  File "/home/ubuntu/./install.py", line 1584, in <module>
    main(args)
  File "/home/ubuntu/./install.py", line 1367, in main
    download_url(
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

The URL it generates https://github.com/WasmEdge/WasmEdge/releases/download/0.12.1/WasmEdge-0.12.1-ubuntu20.04_aarch64.tar.gz is indeed not present and gives a 404

### Expected

Download and install as expected

## Environment

- Hardware Architecture: aarch64
- Operating system: Ubuntu 22.04

## Steps to Reproduce

- Install standard Ubuntu 22.04 AMI on a EC2 t4g.2xl VM. I used the official AMI in us-east-2
- Run `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash`

**Comment by dyasny** [comment]
as a workaround `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -- --dist manylinux2014` seems to be doing the job

**Comment by hydai** [comment]
Hi @dyasny 
Thanks for raising this. We will not release the ubuntu20.04 version on the aarch64 platform. Instead, we would like to ask users to use the manylinux2014 aarch64 version. So the installer will need to update to fix this.

Hi @SAtacker 
I am sorry that I missed that we would not have the aarch64 version for the ubuntu20.04 release assets. If users are on Ubuntu with the aarch64 platform, please use the manylinux2014 one instead. The reason is from here: https://github.com/WasmEdge/WasmEdge/issues/2595#issuecomment-1592460709 
Since PyTorch is not releasing on the Linux aarch64 platform, we will not have such a c++abi issue here.

**Comment by dyasny** [comment]
Thanks @hydai will the issue remain open until the installer is fixed?

**Comment by hydai** [comment]
Yes, please use the workaround you found currently. And this issue should be closed after a PR is merged.

**Comment by dyasny** [comment]
Thanks, I've got some extra "if"s in my pipeline because of this issue, so I want to be sure it's fixed before I remove the unneeded code.

**Comment by SAtacker** [comment]
> Hi @dyasny Thanks for raising this. We will not release the ubuntu20.04 version on the aarch64 platform. Instead, we would like to ask users to use the manylinux2014 aarch64 version. So the installer will need to update to fix this.
> 
> Hi @SAtacker I am sorry that I missed that we would not have the aarch64 version for the ubuntu20.04 release assets. If users are on Ubuntu with the aarch64 platform, please use the manylinux2014 one instead. The reason is from here: [#2595 (comment)](https://github.com/WasmEdge/WasmEdge/issues/2595#issuecomment-1592460709) Since PyTorch is not releasing on the Linux aarch64 platform, we will not have such a c++abi issue here.

Thanks for reporting this. I'll create a PR ASAP.

**Comment by hydai** [comment]
I found that the issue still needs to be resolved. And someone encounters the same issue on Ubuntu 20.04. I am going to reopen it and figure it out.

**Comment by hydai** [comment]
Hi @dyasny 
This should be fixed now. I have checked it works on ubuntu20.04 and ubuntu22.04 on the arm64 platform.

**Comment by dyasny** [comment]
@hydai thank you sir
