### ISSUE TITLE
Can't install WasmEdge on MacOS M2 chip

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#2641]
## Description

I used the following command line to install WasmEdge.
```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
```

### Current State

The error messages are the following:
```
Using Python: /usr/bin/python3 
Compatible with current configuration
Running Uninstaller
WARNING - SHELL variable not found. Using zsh as SHELL
shell configuration updated
Downloading WasmEdge
Traceback (most recent call last):
  File "<stdin>", line 1587, in <module>
  File "<stdin>", line 1370, in main
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
### Expected

Installed WasmEdge successfully

## Environment

- Hardware Architecture: Apple M2
- Operating system: macOS 13.0

**Comment by alabulei1** [comment]
@SAtacker Could you please take a look?

**Comment by SAtacker** [comment]
> @SAtacker Could you please take a look?

Could you please pass the debug flag and post the log?

**Comment by apepkuss** [comment]
@alabulei1 According to the error message "HTTP Error 404: Not Found", is it possible that the url is blocked? Turn on VPN and try again.

**Comment by hydai** [comment]
I know what's going on. The postfix of the Apple Silicon model should be `arm64`. However, I use `aarch64` on the CI release workflow. I just renamed the release assets, it should work now.

**Comment by SAtacker** [comment]
> I know what's going on. The postfix of the Apple Silicon model should be `arm64`. However, I use `aarch64` on the CI release workflow. I just renamed the release assets, it should work now.

Thanks hydai, appreciate it.
