### ISSUE TITLE
Potential Uninitialized Memory Usage in WasmEdge

### ISSUE THREAD

**Issue by khagankhan** [WasmEdge/WasmEdge#3014]
### Summary

A MemorySanitizer warning is triggered when running a WasmEdge tool with a specific .wasm file. The warning indicates a `use-of-uninitialized-value within the std::filesystem::path` destructor, which is invoked in the `WasmEdge::Plugin::Plugin::getDefaultPluginPaths[abi:cxx11]()` function.

I believe the issue may be related to in `WasmEdge/lib/plugin/plugin.cpp`

```
// ...
auto LibPath = std::filesystem::u8path(DLInfo.dli_fname)
                       .parent_path()
                       .lexically_normal();
// ...
```

### Current State

MemorySanitizer warning is triggered, indicating a use-of-uninitialized-value in the `std::filesystem::path` destructor, specifically in the `std::unique_ptr<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>::~unique_ptr()` function.

The full MSAN log:

```
==2902116==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fa331ba47cf in std::unique_ptr<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>::~unique_ptr() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:360:6
    #1 0x7fa331d2b49c in std::filesystem::__cxx11::path::_List::~_List() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:647:24
    #2 0x7fa331d2b49c in std::filesystem::__cxx11::path::~path() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:313:21
    #3 0x7fa331d2b49c in WasmEdge::Plugin::Plugin::getDefaultPluginPaths[abi:cxx11]() /root/wasmoi/targets/WasmEdge/lib/plugin/plugin.cpp:254:20
    #4 0x7fa331c1594f in WasmEdge::Driver::DriverToolOptions::add_option(WasmEdge::PO::ArgumentParser&) /root/wasmoi/targets/WasmEdge/include/driver/tool.h:147:29
    #5 0x7fa331c139eb in WasmEdge::Driver::UniTool(int, char const**, WasmEdge::Driver::ToolType) /root/wasmoi/targets/WasmEdge/lib/driver/uniTool.cpp:33:17
    #6 0x55f7e23463cb in main /root/wasmoi/targets/WasmEdge/tools/wasmedge/wasmedge.cpp:18:10
    #7 0x7fa331424d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7fa331424e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #9 0x55f7e22be2b4 in _start (/root/wasmoi/targets/WasmEdge/build/tools/wasmedge/wasmedge+0x1f2b4) (BuildId: 910013d9e5a818a491833d9f384ea736e3731232)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:360:6 in std::unique_ptr<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>::~unique_ptr()
Exiting
```

### Expected State

`WasmEdge` tool should execute without any MemorySanitizer warnings, indicating that all memory is properly initialized and managed.

[potential_bug.wat.txt](https://github.com/WasmEdge/WasmEdge/files/13258601/potential_bug.wat.txt)
[potential_bug.wasm.txt](https://github.com/WasmEdge/WasmEdge/files/13258602/potential_bug.wasm.txt)

`cat potential_bug.wat` (Please remove `.txt` extesnion when to save):

```wasm
(module (memory $mem 1) (table 0 funcref)
   (elem (i32.const 0))
   (func
    $main
    (export "_main")
    (result i32)
    (local $i32_storage i32)
    (local $i64_storage i64)
    (local $f32_storage f32)
    (local $f64_storage f64)
    i32.const
    82
    i32.const
    33
    i32.load8_s
    offset=71
    align=1
    i32.store
    offset=12
    align=2
    i32.const
    185
    i32.load16_u
    offset=75
    align=1
    i32.extend8_s
    br
    0))
```

### Reproduction steps

1. Build with options: 'Build using the following script':

```bash
#!/bin/env bash

GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

handle_error() {
    if [ $? -ne 0 ]; then
        echo -e "${RED}Error occurred in the previous step. Exiting...${RESET}"
        exit 1
    fi
}

install_wasmedge() {
    TARGET_DIR="../../targets/"
    mkdir -p "$TARGET_DIR"
    handle_error

    cd "$TARGET_DIR"
    handle_error
    
    echo -e "${GREEN}Cloning WasmEdge...${RESET}"
    git clone https://github.com/WasmEdge/WasmEdge.git
    handle_error

    cd WasmEdge
    handle_error

    mkdir -p build
    handle_error

    cd build
    handle_error

   
    echo -e "${GREEN}Installing dependencies...${RESET}"
    sudo apt update && sudo apt install -y \
       software-properties-common \
       cmake \
       libboost-all-dev \
       llvm-14-dev \
       liblld-14-dev 
    handle_error

    echo -e "${GREEN}Configuring with CMake...${RESET}"
    CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake .. \
    -DCMAKE_C_COMPILER_RANLIB=/usr/bin/ranlib \
    -DCMAKE_CXX_COMPILER_RANLIB=/usr/bin/ranlib \
    -DCMAKE_C_COMPILER_AR=/usr/bin/ar \
    -DCMAKE_CXX_COMPILER_AR=/usr/bin/ar \
    -DCMAKE_C_COMPILER_LAUNCHER=/usr/bin/clang \
    -DCMAKE_C_COMPILER_AR=/usr/bin/ar  \
    -DCMAKE_CXX_COMPILER_LAUNCHER=/usr/bin/clang++ \
    -DCMAKE_C_FLAGS="-fsanitize=memory,undefined -g" \
    -DCMAKE_CXX_FLAGS="-fsanitize=memory,undefined -g"
    handle_error

   
    echo -e "${GREEN}Compiling...${RESET}"
    make -j$(nproc)
    handle_error 
    echo -e "${GREEN}WasmEdge installed successfully here: ../../targets/WasmEdge${RESET}"
    echo -e "${GREEN}[*] ----------- < Memory Sanitizer is activated! > ----------- [*]${RESET}"	

}

install_wasmedge
```

2. Execute with flags 'None is required'
3. Execute with inputs `/path/to/WasmEdge/build/tools/wasmedge/wasmedge potential_bug.wasm`

   `potential_bug.wat` and `potential_bug.wasm` - the input files whose execution found the issue have been added to the "Expected State" section.

   Save the `potential_bug.wat` (Remove .txt extension)
   Install and build WABT toolkit (`wat2wasm` from WABT can be used to convert the `potential_bug.wat` into `potential_bug.wasm` using: `wat2wasm potential_bug.wat -o potential_bug.wasm.` 
   I have also added `potential_bug.wasm` that obviates the need to use download, build and use of `wat2wasm`)
   Run: `/path/to/WasmEdge/build/tools/wasmedge/wasmedge potential_bug.wasm`

4. Get error

### Any logs you want to share for showing the specific issue

`MSAN log:`

```bash
==2902116==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fa331ba47cf in std::unique_ptr<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>::~unique_ptr() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:360:6
    #1 0x7fa331d2b49c in std::filesystem::__cxx11::path::_List::~_List() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:647:24
    #2 0x7fa331d2b49c in std::filesystem::__cxx11::path::~path() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:313:21
    #3 0x7fa331d2b49c in WasmEdge::Plugin::Plugin::getDefaultPluginPaths[abi:cxx11]() /root/wasmoi/targets/WasmEdge/lib/plugin/plugin.cpp:254:20
    #4 0x7fa331c1594f in WasmEdge::Driver::DriverToolOptions::add_option(WasmEdge::PO::ArgumentParser&) /root/wasmoi/targets/WasmEdge/include/driver/tool.h:147:29
    #5 0x7fa331c139eb in WasmEdge::Driver::UniTool(int, char const**, WasmEdge::Driver::ToolType) /root/wasmoi/targets/WasmEdge/lib/driver/uniTool.cpp:33:17
    #6 0x55f7e23463cb in main /root/wasmoi/targets/WasmEdge/tools/wasmedge/wasmedge.cpp:18:10
    #7 0x7fa331424d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7fa331424e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #9 0x55f7e22be2b4 in _start (/root/wasmoi/targets/WasmEdge/build/tools/wasmedge/wasmedge+0x1f2b4) (BuildId: 910013d9e5a818a491833d9f384ea736e3731232)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:360:6 in std::unique_ptr<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>::~unique_ptr()
Exiting
```

`gdb log:`

```
root@node9:~/wasmoi/fuzz/output/f0/crashes# gdb --args /root/wasmoi/targets/WasmEdge/build/tools/wasmedge/wasmedge test.wasm
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /root/wasmoi/targets/WasmEdge/build/tools/wasmedge/wasmedge...
(gdb) br /root/wasmoi/targets/WasmEdge/lib/plugin/plugin.cpp:254
No source file named /root/wasmoi/targets/WasmEdge/lib/plugin/plugin.cpp.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (/root/wasmoi/targets/WasmEdge/lib/plugin/plugin.cpp:254) pending.
(gdb) run
Starting program: /root/wasmoi/targets/WasmEdge/build/tools/wasmedge/wasmedge test.wasm
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, WasmEdge::Plugin::Plugin::getDefaultPluginPaths[abi:cxx11]() () at /root/wasmoi/targets/WasmEdge/lib/plugin/plugin.cpp:254
254	    auto LibPath = std::filesystem::u8path(DLInfo.dli_fname)
(gdb) step
std::filesystem::__cxx11::u8path<char const*, std::filesystem::__cxx11::path, char> (__source=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:799
799	      return path{ __source };
(gdb) step
std::filesystem::__cxx11::path::path<char const*, std::filesystem::__cxx11::path> (this=0x7fffffffd5f8, __source=@0x7fffffffd6d8: 0x7ffff7fbb310 "/root/wasmoi/targets/WasmEdge/build/tools/wasmedge/../../lib/api/libwasmedge.so.0") at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:290
290	      { _M_split_cmpts(); }
(gdb) step
289	      : _M_pathname(_S_convert(__detail::__effective_range(__source)))
(gdb) step
std::filesystem::__cxx11::__detail::__effective_range<char const*> (__source=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:175
175		return basic_string_view{&*__source};
(gdb) step
std::basic_string_view<char, std::char_traits<char> >::basic_string_view (__str=0x7ffff7fbb310 "/root/wasmoi/targets/WasmEdge/build/tools/wasmedge/../../lib/api/libwasmedge.so.0", this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/string_view:132
132	      : _M_len{traits_type::length(__str)},
(gdb) step
std::char_traits<char>::length (__s=0x7ffff7fbb310 "/root/wasmoi/targets/WasmEdge/build/tools/wasmedge/../../lib/api/libwasmedge.so.0")
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/char_traits.h:399
399		return __builtin_strlen(__s);
(gdb) step
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::basic_string_view<char, std::char_traits<char> >, void> (this=0x7fffffffd5f8, __a=..., __t=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:665
^[[A
665		: basic_string(__sv_wrapper(_S_to_string_view(__t)), __a) { }
(gdb) step
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=<optimized out>, __svw=..., __a=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:154
154	      : basic_string(__svw._M_sv.data(), __svw._M_sv.size(), __a) { }
(gdb) step
std::filesystem::__cxx11::path::path<char const*, std::filesystem::__cxx11::path> (this=0x7fffffffd5f8, __source=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:288
288	      path(_Source const& __source, format = auto_format)
(gdb) step
290	      { _M_split_cmpts(); }
(gdb) step
WasmEdge::Plugin::Plugin::getDefaultPluginPaths[abi:cxx11]() () at /root/wasmoi/targets/WasmEdge/lib/plugin/plugin.cpp:255
255	                       .parent_path()
(gdb) step
256	                       .lexically_normal();
(gdb) step
254	    auto LibPath = std::filesystem::u8path(DLInfo.dli_fname)
(gdb) step
std::filesystem::__cxx11::path::~path (this=0x7fffffffd5a8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:313
313	    ~path() = default;
(gdb) step
std::filesystem::__cxx11::path::_List::~_List (this=0x7fffffffd5c8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:647
647	      ~_List() = default;
(gdb) step
std::unique_ptr<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>::~unique_ptr (this=0x7fffffffd5c8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:356
356	      {
(gdb) step
359		auto& __ptr = _M_t._M_ptr();
(gdb) step
std::__uniq_ptr_impl<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>::_M_ptr (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:172
172	      pointer&   _M_ptr() { return std::get<0>(_M_t); }
(gdb) step
std::get<0ul, std::filesystem::__cxx11::path::_List::_Impl*, std::filesystem::__cxx11::path::_List::_Impl_deleter> (__t=std::tuple containing = {...}) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/tuple:1394
1394	    { return std::__get_helper<__i>(__t); }
(gdb) step
std::unique_ptr<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>::~unique_ptr (this=0x7fffffffd5c8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:360
360		if (__ptr != nullptr)
(gdb) step
==2902220==WARNING: MemorySanitizer: use-of-uninitialized-value
[Detaching after fork from child process 2902225]
^[[A    #0 0x7ffff761e7cf in std::unique_ptr<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>::~unique_ptr() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:360:6
    #1 0x7ffff77a549c in std::filesystem::__cxx11::path::_List::~_List() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:647:24
    #2 0x7ffff77a549c in std::filesystem::__cxx11::path::~path() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/fs_path.h:313:21
    #3 0x7ffff77a549c in WasmEdge::Plugin::Plugin::getDefaultPluginPaths[abi:cxx11]() /root/wasmoi/targets/WasmEdge/lib/plugin/plugin.cpp:254:20
    #4 0x7ffff768f94f in WasmEdge::Driver::DriverToolOptions::add_option(WasmEdge::PO::ArgumentParser&) /root/wasmoi/targets/WasmEdge/include/driver/tool.h:147:29
    #5 0x7ffff768d9eb in WasmEdge::Driver::UniTool(int, char const**, WasmEdge::Driver::ToolType) /root/wasmoi/targets/WasmEdge/lib/driver/uniTool.cpp:33:17
    #6 0x5555555fb3cb in main /root/wasmoi/targets/WasmEdge/tools/wasmedge/wasmedge.cpp:18:10
    #7 0x7ffff6e9ed8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7ffff6e9ee3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #9 0x5555555732b4 in _start (/root/wasmoi/targets/WasmEdge/build/tools/wasmedge/wasmedge+0x1f2b4) (BuildId: 910013d9e5a818a491833d9f384ea736e3731232)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:360:6 in std::unique_ptr<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>::~unique_ptr()
Exiting
[Inferior 1 (process 2902220) exited with code 01]
```

### Components

CLI

### WasmEdge Version or Commit you used

0.13.5-2-ga9b19db0

### Operating system information

Ubuntu 22.04.3

### Hardware Architecture

x86_64

### Compiler flags and options

It was added to to the "Reproduction steps" section.

## Additional information

A combination of AFL++ and Wasmlike, an Xsmith-based random program generator produced the snippet of code that found the issue. [Xsmith Project](https://www.flux.utah.edu/project/xsmith)

**Comment by dannypsnl** [comment]
I believe this will irrelevant to wasmedge's version, but clang's version, can you provide the llvm information for this issue?

**Comment by dannypsnl** [comment]
Never mind, I think you can add a check to ensure `DLInfo.dli_fname` is not null, would you like to send a PR?

**Comment by khagankhan** [comment]
Hey! Thanks for your response! Can you assign this to me?

**Comment by dannypsnl** [comment]
Sure

**Comment by dannypsnl** [comment]
### Tasks

- [ ] If `DLInfo` can't be proper initialized, provide a proper error reporting.
