### ISSUE TITLE
bug: AWS Sample not working

### ISSUE THREAD

**Issue by barum** [WasmEdge/WasmEdge#3024]
### Summary

I followed all the instructions  but the  AWS sample, even localy, does not work.

```08 Nov 2023 15:43:39,186 [INFO] (rapid) exec '/var/runtime/bootstrap' (cwd=/var/task, handler=)
08 Nov 2023 15:45:15,569 [INFO] (rapid) extensionsDisabledByLayer(/opt/disable-extensions-jwigqn8j) -> stat /opt/disable-extensions-jwigqn8j: no such file or directory
08 Nov 2023 15:45:15,569 [INFO] (rapid) Configuring and starting Operator Domain
08 Nov 2023 15:45:15,569 [INFO] (rapid) Starting runtime domain
08 Nov 2023 15:45:15,570 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
08 Nov 2023 15:45:15,570 [INFO] (rapid) Starting runtime without AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN , Expected?: false
START RequestId: d98b552a-1281-4d32-891c-d1d55b345ff9 Version: $LATEST
2023-11-08T15:45:15.683Z        409935d8-dd5a-4112-a34c-be10ae894ee2    ERROR   Invoke Error      {"errorType":"TypeError","errorMessage":"Cannot read properties of undefined (reading 'match')","stack":["TypeError: Cannot read properties of undefined (reading 'match')","    at exports.handler (/var/task/hello.js:24:46)","    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"]}
END RequestId: 409935d8-dd5a-4112-a34c-be10ae894ee2
REPORT RequestId: 409935d8-dd5a-4112-a34c-be10ae894ee2  Init Duration: 1.02 ms  Duration: 115.63 ms       Billed Duration: 116 ms Memory Size: 3008 MB    Max Memory Used: 3008 MB
```

### Reproduction steps

```bash
1. Build with options '...'
2. Execute with flags '....'
3. Execute with inputs '....'
4. Get error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Components

Others

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

Mac 

### Hardware Architecture

arm64

**Comment by hydai** [comment]
Hi @barum 
Which example do you follow?
I cannot get any related information from your log. Could you please share more information?

**Comment by hydai** [comment]
Lack of information. Closing it. Please provide more details and re-open this issue.
