### ISSUE TITLE
Can't install WasmEdge and ggml plugin via the installer

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#3359]
### Summary

When I execute the following command to install WasmEdge and ggml plugin on my macOS, I can't install WasmEdge successfully.

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_nn-ggml
```

The output is the following:

```
Using Python: /Users/alabulei/miniconda3/bin/python3 
INFO    - CUDA is only supported on Linux
INFO    - CUDA is only supported on Linux
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
INFO    - Running Uninstaller
WARNING - SHELL variable not found. Using zsh as SHELL
INFO    - shell configuration updated
INFO    - Downloading WasmEdge
Traceback (most recent call last):
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/alabulei/miniconda3/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/alabulei/miniconda3/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/alabulei/miniconda3/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/alabulei/miniconda3/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/Users/alabulei/miniconda3/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/Users/alabulei/miniconda3/lib/python3.11/http/client.py", line 1458, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/Users/alabulei/miniconda3/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1896, in <module>
  File "<stdin>", line 1643, in main
  File "<stdin>", line 44, in wrap_download_url
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alabulei/miniconda3/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 54] Connection reset by peer>
```

### Reproduction steps

Run the following command to install WasmEdge and ggml plugin on macOS

```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_nn-ggml
```

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

no

### Operating system information

macOS 14.2.1 (23B81)

### Hardware Architecture

M2

**Comment by hydai** [comment]
I don't think we should fix it because this is an issue with Python and certifi. 
If the python installer is not working, use installer v2, a pure bash installer, instead.
