### ISSUE TITLE
bug: AOT compiled AssemblyScript contract with host import error "out of bounds memory access"

### ISSUE THREAD

**Issue by loredanacirstea** [WasmEdge/WasmEdge#3857]
### Summary

Executing an AOT compiled AssemblyScript contract with a host import that returns an ArrayBuffer gives me "out of bounds memory access".
Without AOT compilation, the contract is executed correctly.

The "out of bounds memory access" error happens after the host import finishes.

### Expected State

AOT-compiled contracts should behave like WASM-interpreted contracts.

### Reproduction steps

Reproduction code: https://github.com/loredanacirstea/wasmedge-aot-tests

```
git clone https://github.com/loredanacirstea/wasmedge-aot-tests.git
cd wasmedge-aot-tests
cd as
npm run asbuild
cd ..

go run .
```
Code entry point, where I execute both .wasm & .so examples: https://github.com/loredanacirstea/wasmedge-aot-tests/blob/master/app.go#L156-L157

### Any logs you want to share for showing the specific issue

```
[2024-10-31 15:19:05.512] [error] execution failed: out of bounds memory access, Code: 0x88
[2024-10-31 15:19:05.513] [error]     When executing function name: "main"
panic: out of bounds memory access
```

### Components

Others

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

macOS 15.1

### Hardware Architecture

arm64

**Comment by loredanacirstea** [comment]
When I execute the above example I get 2 different results:

```
CGO_LDFLAGS='-Wl,-rpath,/Users/user/.wasmedge/lib' go run .
# example/app
ld: warning: duplicate -rpath '/Users/user/.wasmedge/lib' ignored
wasmx: console.log: --main-- - as wasm example
wasmx: console.log: --calldraw-- - as wasm example
wasmx: console.log: --calldstr--somecalldata - as wasm example
as/build/release.wasm test success
wasmx: console.log: --main-- - as AOT example
libc++abi: terminating due to uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
signal: abort trap
```

```
CGO_LDFLAGS='-Wl,-rpath,/Users/user/.wasmedge/lib' go run .
# example/app
ld: warning: duplicate -rpath '/Users/user/.wasmedge/lib' ignored
wasmx: console.log: --main-- - as wasm example
wasmx: console.log: --calldraw-- - as wasm example
wasmx: console.log: --calldstr--somecalldata - as wasm example
as/build/release.wasm test success
wasmx: console.log: --main-- - as AOT example
[2024-11-03 12:40:40.082] [error] execution failed: out of bounds memory access, Code: 0x88
[2024-11-03 12:40:40.082] [error]     When executing function name: "main"
panic: out of bounds memory access

goroutine 1 [running]:
main.runExampleAssemblyScriptAOT({0x1400001e044, 0x2d})
        /Users/user/dev/blockchain/wasmedge-aot-tests/app.go:141 +0x290
main.main()
        /Users/user/dev/blockchain/wasmedge-aot-tests/app.go:157 +0x40
exit status 2
```

**Comment by hydai** [comment]
Hi @loredanacirstea 
Thanks for raising this. I found you are using an older version of WasmEdge.
Please try to upgrade the version from 0.13.4 to 0.13.5 or 0.14.1. Because there are lots of AOT-related bugs that were fixed during these versions,

**Comment by loredanacirstea** [comment]
@hydai I did not upgrade, because I use Golang bindings and the last version of https://github.com/second-state/WasmEdge-go is `0.13.4`

Any plans to upgrade `WasmEdge-go` to `0.14.1` ?

Using `WasmEdge-go v0.13.4` with 
```
wasmedge --version
wasmedge version 0.14.1
 (plugin "wasi_logging") version 0.1.0.0
```

and running my simple example, gives me this error 
(I assume the go bindings were not updated to work with 0.14.1 - please correct me if I am wrong):

```
CGO_LDFLAGS='-Wl,-rpath,/Users/user/.wasmedge/lib' go run .
# example/app
ld: warning: duplicate -rpath '/Users/user/.wasmedge/lib' ignored
[2024-11-04 10:00:31.935] [error] instantiation failed: incompatible import type, Code: 0x301
[2024-11-04 10:00:31.935] [error]     Mismatched function type. Expected: FuncType {params{i32} returns{}} , Got: FuncType {params{type_index} returns{}}
[2024-11-04 10:00:31.935] [error]     When linking module: "env" , function name: "console.log"
[2024-11-04 10:00:31.935] [error]     At AST node: import description
[2024-11-04 10:00:31.935] [error]     At AST node: import section
[2024-11-04 10:00:31.935] [error]     At AST node: module
panic: incompatible import type

goroutine 1 [running]:
main.runExampleAssemblyScript({0x1400001e044, 0x2d})
        /Users/user/dev/wasmedge-aot-tests/app.go:109 +0x20c
main.main()
        /Users/user/dev/wasmedge-aot-tests/app.go:156 +0x34
exit status 2
```

Relevant example code:
```
# release.wasm
(import "env" "console.log" (func $~lib/bindings/dom/console.log (param i32)))

# wasmx.go host import
functype_i32_ := wasmedge.NewFunctionType(
  []wasmedge.ValType{wasmedge.ValType_I32},
  []wasmedge.ValType{},
)
env.AddFunction("console.log", wasmedge.NewFunction(functype_i32_, asConsoleLog, context, 0))

```

**Comment by q82419** [comment]
@loredanacirstea  We'll update WasmEdge-Go to `0.13.5` in these days.
But I think the AOT bugs fixed within the `0.14.0` versions.
But the API changes from the `0.13.x` to `0.14.x`, so I think we will not have `0.14.x` go binding so quickly.

**Comment by q82419** [comment]
Please follow this to update wasmedge-go:
https://wasmedge.org/docs/embed/go/reference/upgrade_to_0.14.0/

This may be fixed in #4052 or earlier.
Tested that this issue is fixed in the `master` branch.
Please try the 0.15.0 in the future, or you can build from source with the `master` of WasmEdge with wasmedge-go v0.14.0.
